# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

-  task: DownloadSecureFile@1
  name: 'github'
  inputs:
    secureFile: 'github'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'github.com,140.82.113.4'
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIrVI7mvTeZZM+Jc7Vp8nHKZ544pu/Et7umxsYYKaKseYoc197HHId6AOjM2dgAiitfRrrwK9uYdhRfgry8Xn0ts2Lf7VtgHoCfGOgru+rdp093fKIZ/cj9pa5c49sOHPv3VVt+n4sdM04O67fZAP50JhFF3/Z1kQXjIrYr2buYMD95vKFt7xqSc9Jy+kBRSzU97CfoiPgCCPui445nqeMX6dXU0x0A82KydgK9/8qOgXOy4c9XZenvgfa6zw0T/rnNLziaUZXzcHckseak07S2Iy3yZSqCWrlaObK6q8KhJO5hCONclrpqgpc+vDzox0lYtjJlC6fdDPmLGyvT3DN samar@DESKTOP-C30U090'
    sshKeySecureFile: 'github'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @vue/cli
    npm install
    npm run build
  displayName: 'run build'

- script: |
    cd dist

    git config --global user.email ""
    git config --global user.name "ADO Bot"

    git init
    git remote add origin "git@github.com:cityclicker/cityclicker.github.io.git"
    git add .
    git commit -m "update live site"
    git push origin master --force 
  displayName: 'push to site'

